<?php
namespace OneAuth\Controller;

use OneAuth\DataStore\DataStoreInterface;
use OneAuth\Request\RevokeParams;
use OneAuth\Request\TokenParams;
use OneAuth\ResponseType\AccessToken;
use OneAuth\Server;
use Psr\Http\Message\ResponseInterface as ResponseInterface;
use Psr\Http\Message\ServerRequestInterface as RequestInterface;

class TokenController
{
    const validationMessages = [
        'invalid_grant_type' => 'Invalid grant type',
    ];

    protected $dataStore;

    public function __construct(DataStoreInterface $dataStore)
    {
        $this->dataStore = $dataStore;
    }

    /**
     * Handle request to obtain authorization token.
     * The request body should have this data:
     *  - grant_type:            must be 'authorization_code'
     *  - code:                  authorization code obtained from the authorization server
     *  - client_id:             must match cliendId of the authorization code
     *  - redirect_url:          must match redirectUrl of the authorization code
     *  - code_verifier:         plain text code challenge generated by the SPA (recommended for PKCE)
     */
    public function handleTokenRequest(RequestInterface $request, ResponseInterface $response): ResponseInterface
    {
        $params = new TokenParams($this->dataStore, $request);
        $validationErrors = $params->getValidationErrors();
        $authorizationCode = $params->getAuthorizationCode();

        if (!empty($validationErrors)) {
            return Server::withJson($response, ['error' => implode(', ', $validationErrors)])->withStatus(400);
        }

        $handler = null;
        switch ($params->get('grant_type')) {
            case AccessToken::GRANT_TYPE:
                $handler = new AccessToken($this->dataStore);
                break;
        }

        if (!$handler) {
            throw new \Exception(static::validationMessages['invalid_grant_type']);
        }

        // delete authorization code as it is for 1 time use only
        $this->dataStore->deleteAuthorizationCode($params->get('code'));

        return $handler->handle($params, $response, $authorizationCode);
    }

    /**
     * Handle request to revoken access token.
     * The request body should have this data:
     *  - access_token:          access token to be revoked
     *  - client_id:             must match cliendId of the token
     *  - all_for_user:          optional, if present, revoke all tokens for the user
     */
    public function handleRevokeRequest(RequestInterface $request, ResponseInterface $response): ResponseInterface
    {
        $params = new RevokeParams($this->dataStore, $request);
        $validationErrors = $params->getValidationErrors();
        $accessToken = $params->getValidatedToken();

        if (!empty($validationErrors)) {
            return Server::withJson($response, ['error' => implode(', ', $validationErrors)])->withStatus(400);
        }

        if ($params->get('all_for_user')) {
            $accessToken->deleteAllForUser();
        } else {
            $accessToken->delete();
        }

        // always return 200 OK
        return $response->withStatus(200, 'OK');
    }
}
