<?php
namespace OAuth2\Controller;

use OAuth2\DataStore\DataStoreInterface;
use OAuth2\Request\TokenParams;
use OAuth2\ResponseType\AccessToken;
use OAuth2\Server;
use Psr\Http\Message\ResponseInterface as ResponseInterface;
use Psr\Http\Message\ServerRequestInterface as RequestInterface;

class TokenController
{
    const validationMessages = [
        'invalid_grant_type' => 'Invalid grant type',
    ];

    protected $dataStore;

    public function __construct(DataStoreInterface $dataStore)
    {
        $this->dataStore = $dataStore;
    }

    /**
     * Handle request to obtain authorization token.
     * The request body should have this data:
     *  - grant_type:            must be 'authorization_code'
     *  - code:                  authorization code obtained from the authorization server
     *  - client_id:             must match cliendId of the authorization code
     *  - redirect_url:          must match redirectUrl of the authorization code
     *  - code_verifier:         plain text code challenge generated by the SPA (recommended for PKCE)
     */
    public function handleTokenRequest(RequestInterface $request, ResponseInterface $response, $user_id = null): ResponseInterface
    {
        $params = new TokenParams($this->dataStore, $request);
        $validationErrors = $params->getValidationErrors();

        if (!empty($validationErrors)) {
            return Server::withJson($response, ['error' => implode(', ', $validationErrors)]);
        }

        $handler = null;
        switch ($params->get('grant_type')) {
            case AccessToken::GRANT_TYPE:
                $handler = new AccessToken($this->dataStore);
                break;
        }

        if (!$handler) {
            throw new \Exception(static::validationMessages['invalid_grant_type']);
        }

        // delete authorization code as it is for 1 time use only
        $this->dataStore->deleteAuthorizationCode($params->get('code'));

        return $handler->handle($params, $response, $user_id);
    }
}
